spring:
  application:
    name: booking-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888
  cloud:
    config:
      fail-fast: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true